# Generated by Django 4.2.7 on 2023-12-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.JSONField()),
                ('name', models.CharField(max_length=50)),
                ('cfa_url', models.CharField(max_length=100)),
                ('vetstreet_url', models.CharField(max_length=100)),
                ('vcahospitals_url', models.CharField(max_length=100)),
                ('temperament', models.CharField(max_length=400)),
                ('origin', models.CharField(max_length=40)),
                ('country_codes', models.CharField(max_length=20)),
                ('country_code', models.CharField(max_length=4)),
                ('description', models.CharField(max_length=1000)),
                ('life_span', models.CharField(max_length=4)),
                ('indoor', models.IntegerField()),
                ('lap', models.IntegerField()),
                ('alt_names', models.IntegerField()),
                ('adaptability', models.IntegerField()),
                ('affection_level', models.IntegerField()),
                ('child_friendly', models.IntegerField()),
                ('cat_friendly', models.IntegerField()),
                ('dog_friendly', models.IntegerField()),
                ('energy_level', models.IntegerField()),
                ('grooming', models.IntegerField()),
                ('health_issues', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('shedding_level', models.IntegerField()),
                ('social_needs', models.IntegerField()),
                ('stranger_friendly', models.IntegerField()),
                ('vocalisation', models.IntegerField()),
                ('bidability', models.IntegerField()),
                ('experimental', models.IntegerField()),
                ('hairless', models.IntegerField()),
                ('natural', models.IntegerField()),
                ('rare', models.IntegerField()),
                ('rex', models.IntegerField()),
                ('suppressed_tail', models.IntegerField()),
                ('short_legs', models.IntegerField()),
                ('wikipedia_url', models.CharField(max_length=100)),
                ('hypoallergenic', models.IntegerField()),
                ('reference_image_id', models.CharField(max_length=15)),
                ('left', models.JSONField()),
                ('image_url', models.CharField(max_length=100)),
                ('stars', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='DogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.JSONField()),
                ('height', models.JSONField()),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('country_code', models.CharField(max_length=6)),
                ('bred_for', models.CharField(max_length=50)),
                ('breed_group', models.CharField(max_length=50)),
                ('life_span', models.CharField(max_length=20)),
                ('history', models.CharField(max_length=500)),
                ('temperament', models.CharField(max_length=500)),
                ('origin', models.CharField(max_length=40)),
                ('reference_image_id', models.CharField(max_length=100)),
                ('image', models.JSONField()),
                ('names_list', models.JSONField()),
            ],
        ),
    ]
