# Generated by Django 4.2.7 on 2023-12-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catmodel',
            name='left',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='catmodel',
            name='stars',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='catmodel',
            name='weight',
            field=models.JSONField(default={'imperial': '', 'metric': ''}),
        ),
        migrations.AlterField(
            model_name='dogmodel',
            name='height',
            field=models.JSONField(default={'imperial': '', 'metric': ''}),
        ),
        migrations.AlterField(
            model_name='dogmodel',
            name='image',
            field=models.JSONField(default={'height': '', 'id': '', 'url': '', 'width': ''}),
        ),
        migrations.AlterField(
            model_name='dogmodel',
            name='names_list',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='dogmodel',
            name='weight',
            field=models.JSONField(default={'imperial': '', 'metric': ''}),
        ),
    ]
