# Generated by Django 4.2.7 on 2023-12-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_alter_catmodel_left_alter_catmodel_stars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catmodel',
            name='left',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='catmodel',
            name='stars',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='catmodel',
            name='weight',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='dogmodel',
            name='height',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='dogmodel',
            name='image',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='dogmodel',
            name='names_list',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='dogmodel',
            name='weight',
            field=models.JSONField(default=dict),
        ),
    ]
