# Generated by Django 4.2.7 on 2023-12-02 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_remove_catmodel_id_remove_dogmodel_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catmodel',
            name='adaptability',
        ),
        migrations.RemoveField(
            model_name='catmodel',
            name='affection_level',
        ),
        migrations.RemoveField(
            model_name='catmodel',
            name='alt_names',
        ),
        migrations.RemoveField(
            model_name='catmodel',
            name='bidability',
        ),
        migrations.RemoveField(
            model_name='catmodel',
            name='cat_friendly',
        ),
        migrations.RemoveField(
            model_name='catmodel',
            name='child_friendly',
        ),
        migrations.RemoveField(
            model_name='catmodel',
            name='dog_friendly',
        ),
        migrations.RemoveField(
            model_name='catmodel',
            name='energy_level',
        ),
        migrations.RemoveField(
            model_name='catmodel',
            name='experimental',
        ),
        migrations.RemoveField(
            model_name='catmodel',
            name='grooming',
        ),
        migrations.RemoveField(
            model_name='catmodel',
            name='hairless',
        ),
        migrations.RemoveField(
            model_name='catmodel',
            name='health_issues',
        ),
        migrations.RemoveField(
            model_name='catmodel',
            name='hypoallergenic',
        ),
        migrations.RemoveField(
            model_name='catmodel',
            name='indoor',
        ),
        migrations.RemoveField(
            model_name='catmodel',
            name='intelligence',
        ),
        migrations.RemoveField(
            model_name='catmodel',
            name='lap',
        ),
        migrations.RemoveField(
            model_name='catmodel',
            name='natural',
        ),
        migrations.RemoveField(
            model_name='catmodel',
            name='rare',
        ),
        migrations.RemoveField(
            model_name='catmodel',
            name='rex',
        ),
        migrations.RemoveField(
            model_name='catmodel',
            name='shedding_level',
        ),
        migrations.RemoveField(
            model_name='catmodel',
            name='short_legs',
        ),
        migrations.RemoveField(
            model_name='catmodel',
            name='social_needs',
        ),
        migrations.RemoveField(
            model_name='catmodel',
            name='stranger_friendly',
        ),
        migrations.RemoveField(
            model_name='catmodel',
            name='suppressed_tail',
        ),
        migrations.RemoveField(
            model_name='catmodel',
            name='vocalisation',
        ),
    ]
