# Generated by Django 4.2.7 on 2023-12-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_remove_catmodel_adaptability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catmodel',
            name='names_list',
            field=models.JSONField(default=list),
        ),
    ]
