# Generated by Django 4.2.7 on 2023-12-03 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_catmodel_names_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catmodel',
            name='names_list',
        ),
        migrations.RemoveField(
            model_name='dogmodel',
            name='names_list',
        ),
    ]
